services:
  app:
    build:
      context: .
      target: base
    command: bin/rails server -b 0.0.0.0
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    ports:
      - "3000:3000"

volumes:
  rubygems:
