default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("DATABASE_USER", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "postgres") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>


development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "voxquad_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "voxquad_test") %>

production:
  primary: &primary_production
    <<: *default
    database: voxquad_production
    username: voxquad
  cache:
    <<: *primary_production
    database: voxquad_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: voxquad_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: voxquad_production_cable
    migrations_paths: db/cable_migrate
